### ISSUE TITLE
Attempting to apply auto reapply does this:

### ISSUE THREAD

**Issue by thatchromeosuser** [MichaelEpicA/RBXTools#14]
An exception occured: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RBXTools.DelegateStorage.RestoreOriginalLauncher()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at RBXTools.Choice.Run()
   at RBXTools.Program.Welcome()

**Comment by Frisk9571** [comment]
skill issue (don't use RBXTools)

**Comment by MichaelEpicA** [comment]
Issue known, already being worked on, it's an issue with the launcher not being updated, and will be coming out soon.

**Comment by thatchromeosuser** [comment]
ty michelle <33
