### ISSUE TITLE
whoops!

### ISSUE THREAD

**Issue by nicholasb3** [MichaelEpicA/RBXTools#2]
replaced oof sound
this is the error it gives me
PLEASE REPORT THIS TO https://github.com/MichaelEpicA/RBXTools/issues! An exception occured: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: The process cannot access the file 'C:\Users\xkass\AppData\Roaming\RBXTools\mods.config' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at RBXTools.Config.CheckIfModHasBeenAddedAlready(String id)
   at RBXTools.Config.WriteMod(String id, String custompath)
   at RBXTools.Program.RestoreOldNoobSoundEffect()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at RBXTools.Choice.Run()
   at RBXTools.Program.Welcome()

**Comment by MichaelEpicA** [comment]
Thanks, gonna look into this...

**Comment by MichaelEpicA** [comment]
Fixed in https://github.com/MichaelEpicA/RBXTools/commit/6892f569bdbc1a46879bdb117cb111a567292081
