### ISSUE TITLE
RBXTools Admin Bug

### ISSUE THREAD

**Issue by MichaelEpicA** [MichaelEpicA/RBXTools#6]
If you input an admin folder in RBXTools, it will not check if it is an admin folder, or reboot you into administrator.

This causes an exception to rise whenever you try to do a single mod to the roblox folder, except clean up.

Picture of the Exception: 
![image](https://user-images.githubusercontent.com/33169033/181872518-d06fe962-5192-44d4-9aab-32afd38efd6d.png)

PLEASE REPORT THIS TO https://github.com/MichaelEpicA/RBXTools/issues! An exception occured: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\disabledRoblox\Versions\version-9045f70ea522489c\content\sounds\ouch.ogg' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.FileInfo.Delete()
   at RBXTools.Program.RestoreOldNoobSoundEffect()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at RBXTools.Choice.Run()
   at RBXTools.Program.Welcome()

(Please Fix)
-Myself

**Comment by MichaelEpicA** [comment]
Fixed in commit: https://github.com/MichaelEpicA/RBXTools/commit/ef9b6798863cc2765f8fe4ce102843b222ba58f7
